apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        config-checksum: PLACEHOLDER
    spec:
      containers:
        - name: main
          image: nginx
          volumeMounts:
            - name: config
              mountPath: "/etc"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: config-map-1
