apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-3
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        config-checksum: PLACEHOLDER
    spec:
      containers:
        - name: main
          image: nginx
          volumeMounts:
            - name: config1
              mountPath: "/etc1"
              readOnly: true
            - name: config2
              mountPath: "/etc2"
              readOnly: true
      volumes:
        - name: config1
          configMap:
            name: config-map-1
        - name: config2
          configMap:
            name: config-map-2